[package]
name = "constellation"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
edition = "2018"
publish = false

[lib]
name = "constellation"
path = "lib.rs"

[dependencies]
background_hang_monitor = { path = "../background_hang_monitor" }
backtrace = "0.3"
bluetooth_traits = { path = "../bluetooth_traits" }
canvas_traits = { path = "../canvas_traits" }
compositing = { path = "../compositing" }
crossbeam-channel = "0.4"
devtools_traits = { path = "../devtools_traits" }
embedder_traits = { path = "../embedder_traits" }
euclid = "0.20"
gfx = { path = "../gfx" }
gfx_traits = { path = "../gfx_traits" }
http = "0.1"
ipc-channel = "0.14"
keyboard-types = "0.5"
layout_traits = { path = "../layout_traits" }
log = "0.4"
media = { path = "../media" }
metrics = { path = "../metrics" }
msg = { path = "../msg" }
net = { path = "../net" }
net_traits = { path = "../net_traits" }
profile_traits = { path = "../profile_traits" }
script_traits = { path = "../script_traits" }
serde = "1.0"
servo_config = { path = "../config" }
servo_rand = {path = "../rand" }
servo_remutex = { path = "../remutex" }
servo_url = { path = "../url" }
style_traits = { path = "../style_traits" }
webgpu = { path = "../webgpu" }
webrender_api = { git = "https://github.com/servo/webrender" }
webrender_traits = { path = "../webrender_traits" }
webxr-api = { git = "https://github.com/servo/webxr", features = ["ipc"] }

[target.'cfg(any(target_os="macos", all(not(target_os = "windows"), not(target_os = "ios"), not(target_os="android"), not(target_arch="arm"), not(target_arch="aarch64"))))'.dependencies]
gaol = "0.2.1"
