[package]
name = "malloc_size_of"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MIT OR Apache-2.0"
publish = false

[lib]
path = "lib.rs"

[features]
servo = [
    "accountable-refcell",
    "content-security-policy",
    "crossbeam-channel",
    "http",
    "hyper_serde",
    "keyboard-types",
    "serde",
    "serde_bytes",
    "string_cache",
    "time",
    "url",
    "uuid",
    "webrender_api",
    "xml5ever",
]

[dependencies]
accountable-refcell = { version = "0.2.0", optional = true }
app_units = "0.7"
content-security-policy = { version = "0.4.0", features = ["serde"], optional = true }
crossbeam-channel = { version = "0.4", optional = true }
cssparser = "0.29"
euclid = "0.20"
hashglobe = { path = "../hashglobe" }
http = { version = "0.2", optional = true }
hyper_serde = { version = "0.13", optional = true }
keyboard-types = { version = "0.6", optional = true }
selectors = { path = "../selectors" }
serde = { version = "1.0.27", optional = true }
serde_bytes = { version = "0.11", optional = true }
servo_arc = { path = "../servo_arc" }
smallbitvec = "2.3.0"
smallvec = "1.0"
string_cache = { version = "0.8", optional = true }
thin-slice = "0.1.0"
time = { version = "0.1.41", optional = true }
tokio = "1"
url = { version = "2.0", optional = true }
uuid = { version = "0.8", features = ["v4"], optional = true }
void = "1.0.2"
webrender_api = { git = "https://github.com/servo/webrender", optional = true }
xml5ever = { version = "0.17", optional = true }
