[package]
name = "profile_traits"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
edition = "2018"
publish = false

[lib]
name = "profile_traits"
path = "lib.rs"

[dependencies]
crossbeam-channel = "0.4"
ipc-channel = "0.14"
log = "0.4"
serde = "1.0"
servo_config = { path = "../config" }
signpost = { git = "https://github.com/pcwalton/signpost.git" }
time = "0.1.41"
