[package]
name = "compositing"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
name = "compositing"
path = "lib.rs"

[features]
default = []
gl = ["gleam", "pixels"]

[dependencies]
canvas = { path = "../canvas" }
crossbeam-channel = "0.4"
embedder_traits = { path = "../embedder_traits" }
euclid = "0.20"
gfx_traits = { path = "../gfx_traits" }
gleam = { version = "0.12", optional = true }
image = "0.23"
ipc-channel = "0.14"
keyboard-types = "0.5"
libc = "0.2"
log = "0.4"
msg = { path = "../msg" }
net_traits = { path = "../net_traits" }
num-traits = "0.2"
pixels = { path = "../pixels", optional = true }
profile_traits = { path = "../profile_traits" }
script_traits = { path = "../script_traits" }
servo-media = { git = "https://github.com/servo/media" }
servo_geometry = { path = "../geometry" }
servo_url = { path = "../url" }
style_traits = { path = "../style_traits" }
time = "0.1.41"
webrender = { git = "https://github.com/servo/webrender", features = ["capture"] }
webrender_api = { git = "https://github.com/servo/webrender" }
webrender_surfman = { path = "../webrender_surfman" }
webxr = { git = "https://github.com/servo/webxr" }

[build-dependencies]
toml = "0.5"
