[package]
name = "webdriver_server"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
edition = "2018"
publish = false

[lib]
name = "webdriver_server"
path = "lib.rs"

[dependencies]
base64 = "0.10"
compositing = { path = "../compositing" }
cookie = "0.12"
crossbeam-channel = "0.4"
euclid = "0.20"
headers = "0.3"
http = "0.2"
image = "0.24"
ipc-channel = "0.14"
keyboard-types = "0.6"
log = "0.4"
msg = { path = "../msg" }
net_traits = { path = "../net_traits" }
pixels = { path = "../pixels" }
script_traits = { path = "../script_traits" }
serde = "1"
serde_json = "1"
servo_config = { path = "../config" }
servo_url = { path = "../url" }
style_traits = { path = "../style_traits" }
uuid = { version = "0.8", features = ["v4"] }
webdriver = "0.44"
